[workspace] 
members = [
	"client",
	"server",
	"beacon",
	"beacon_tests"
]
resolver = "2"

[workspace.dependencies]
tokio-tungstenite = {version = "*", features = ["native-tls"]}
tokio = { version = "1", features = ["full"] }
futures-util = { version = "0.3.31", features = ["sink", "std"]}
